### ISSUE TITLE
Bad URL for Base Modelica

### ISSUE THREAD

**Issue by ViralBShah** [SciML/BaseModelica.jl#16]
In the README it points to example.com

**Comment by jClugstor** [comment]
Oops, should point to https://github.com/modelica/ModelicaSpecification/tree/MCP/0031/RationaleMCP/0031

https://github.com/SciML/BaseModelica.jl/pull/17

**Comment by ViralBShah** [comment]
Is it also possible to fix the build status badge, and add a little bit more information / example into the README?
